FROM node:20

WORKDIR /app

# -----------------------------
# 1. Add corporate certificate
# -----------------------------
# (Ensure you have your company's root CA)
COPY company-rootCA.crt /usr/local/share/ca-certificates/company-rootCA.crt
RUN update-ca-certificates

# Tell Node.js to trust corporate CA
ENV NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt

# -----------------------------
# 2. Set npmrc configuration
# -----------------------------
# Using ARG to inject token securely during build
ARG NPM_TOKEN

RUN npm config set registry "https://centralauth.jfrog.io/artifactory/api/npm/all1y-dashboard-npm-vir/" \
    && npm config set always-auth true \
    && npm config set //centralauth.jfrog.io/artifactory/api/npm/all1y-dashboard-npm-vir/:_authToken=$NPM_TOKEN \
    && npm config set cafile /etc/ssl/certs/ca-certificates.crt \
    && npm config set strict-ssl true

# -----------------------------
# 3. Copy dependency files and install pnpm via corepack
# -----------------------------
COPY package.json pnpm-lock.yaml ./

RUN corepack enable && corepack prepare pnpm@latest --activate

RUN pnpm install --frozen-lockfile

# -----------------------------
# 4. Copy rest of app
# -----------------------------
COPY . .

EXPOSE 3000
CMD ["pnpm", "dev"]

