apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-app-deployment
  labels:
    app: new-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: new-app
  template:
    metadata:
      labels:
        app: new-app
    spec:
      containers:
      - name: new-app
        image: aztest2.azurecr.io/new_app:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: new-app-service
spec:
  type: LoadBalancer
  selector:
    app: new-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
