FROM node:20

WORKDIR /app

# Optional: if you use a private registry
# RUN npm config set registry https://centralauth.jfrog.io/artifactory/api/npm/glb-npm-virtual/

# Copy dependency files first (for Docker cache efficiency)
COPY .npmrc package.json pnpm-lock.yaml ./

# Install dependencies
RUN npm install -g pnpm && pnpm install --frozen-lockfile

# Copy the rest of the app
COPY . .

# Expose the application port
EXPOSE 3000

# Run the app
CMD ["pnpm", "dev"]
